### ISSUE TITLE
Error "detected dubious ownership in repository at '/github/workspace'"

### ISSUE THREAD

**Issue by galoppi** [tomasnorre/typo3-upload-ter#16]
Since 4th of June 2024 I get the error message "detected dubious ownership in repository at '/github/workspace'" on running the github action `tomasnorre/typo3-upload-ter@v2`. Two weeks ago everything worked well.

The log of the action:
```
Preparing upload of release 2.3.7 to TER

fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
Preparing Release
Composer could not detect the root package (vendor/extensionname) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
> sed -i'' -e "s/'version' => ''/'version' => '$(echo ${GITHUB_REF#refs/tags/} | sed 's/v//')'/" ext_emconf.php
> rm -r .github Tests

Publishing version 2.3.7 of extension extensionname
=====================================================

Warning: ] Could not publish version 2.3.7 of extension extensionname.        
           Reason: An error occured on handling the request.                    

##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run tomasnorre/typo3-upload-ter@v2
```

The warning `Composer could not detect the root package (vendor/extensionname) version, defaulting to '1.0.0'.` is also new
and the final warning is unspecific:
`Warning: ] Could not publish version 2.3.7 of extension extensionname.        
           Reason: An error occured on handling the request. `

.github/workflows/release.yml:

```yaml
name: release

on:
  push:
    tags:
      - "**"

jobs:
  terUpload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
```

**Comment by tomasnorre** [comment]
Thanks for your report. Will see if I can figure out what the problem is. Made an update 29th of May. 

Does it still work for you with version 2.0.4? Just to narrow it down to where the problem comes from. I updated it to PHP 8.3, but might have done something wrong in the process.

**Comment by galoppi** [comment]
Hi @tomasnorre,

fix is as follows:

Please add the following lines in Docker/entrypoint.sh after line 2:
```
echo -e "Preparing git configuration (safe.directory)\n";

git config --global --add safe.directory $PWD
```
and rebuild and publish the docker image tomasnorre/typo3teruploader

Best regards

Alex

**Comment by tomasnorre** [comment]
Would you mind, make the PR to get the credit for it directly?

**Comment by galoppi** [comment]
Of course, here it is: https://github.com/tomasnorre/typo3-upload-ter/pull/17

Please keep in mind to rebuild und push the docker image after applying the patch.

**Comment by tomasnorre** [comment]
Is build and released. 
https://github.com/tomasnorre/typo3-upload-ter/releases/tag/v2.0.7 

Thanks for your help.
